// Merik — browser telemetry ingest (Deno).
//
// The one failure class the probe structurally cannot see: the page returns 200,
// uptime reads 100%, and the checkout button throws in the user's browser. This
// is where the client's site tells Merik about it.
//
// POST /functions/v1/collect?k=<asset ingest key>
//   { "events": [ { "kind": "error", "message": "…", "source": "…", "page": "…" } ] }
//
// Deploy with verify_jwt = false. The caller is an anonymous visitor's browser
// on someone else's domain, and it has no Merik session — the key in the query
// string is the whole of the authorisation, which is why it can do exactly one
// thing: append events to the asset it belongs to. It reads nothing, returns
// nothing but a count, and never says whether a key it did not recognise was
// wrong or simply absent.
//
// The key is public by construction — it ships inside the client's JavaScript
// where anyone can read it. So the threat is a stranger posting junk, and the
// defences are shaped for that: no field the caller sends decides which tenant
// the data lands in, counts are computed here rather than accepted, the body is
// size-capped, and everything stored is redacted first (see group.ts).
//
// ponytail: no per-key rate limit. The caps below bound one request; a
// determined flood still costs invocations. Add a counter keyed on the ingest
// key when the usage_events meter shows one is needed — the meter is already
// being written for exactly this kind of question.
import { createClient } from 'jsr:@supabase/supabase-js@2';
import { browserFamily, groupEvents, MAX_EVENTS } from './group.ts';

/** Bigger than any honest batch of 50 truncated events. */
const MAX_BODY_BYTES = 64 * 1024;

// The SDK runs on the client's domain, so this is cross-origin by definition and
// the browser will preflight it. `*` is correct here and not a shortcut: any
// origin may report an error, no credentials are involved, and the response
// carries nothing worth reading back.
const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'content-type',
  'Access-Control-Max-Age': '86400',
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...CORS },
  });

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });
  if (req.method !== 'POST') return json({ ok: false }, 405);

  const key = new URL(req.url).searchParams.get('k') ?? '';
  // Shape-checked before it reaches the database: the key is generated by
  // Postgres as 32 hex characters, so anything else is not a key.
  if (!/^[a-f0-9]{32}$/.test(key)) return json({ ok: false }, 404);

  const raw = await req.text();
  if (raw.length > MAX_BODY_BYTES) return json({ ok: false, error: 'too large' }, 413);

  let body: { events?: unknown };
  try {
    body = JSON.parse(raw);
  } catch {
    return json({ ok: false, error: 'invalid json' }, 400);
  }

  const rows = groupEvents(body.events, browserFamily(req.headers.get('user-agent')));
  if (!rows.length) return json({ ok: true, stored: 0 });

  const admin = createClient(
    Deno.env.get('SUPABASE_URL')!,
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
  );

  const { data: asset } = await admin
    .from('digital_assets')
    .select('id, org_id')
    .eq('ingest_key', key)
    .is('archived_at', null)
    .maybeSingle()
    .returns<{ id: string; org_id: string }>();

  // Same answer as a malformed key. Telling a caller that a key exists but is
  // archived is telling them something about a tenant they cannot see.
  if (!asset) return json({ ok: false }, 404);

  const { error } = await admin.rpc('ingest_frontend_errors', {
    p_asset: asset.id,
    p_rows: rows,
  });
  if (error) {
    console.error('ingest failed', error.message);
    return json({ ok: false }, 500);
  }

  // Metered like every other unit of work in the module — the browser SDK is the
  // one that could get expensive, so it is the one worth counting from day one.
  await admin.from('usage_events').insert({
    org_id: asset.org_id,
    asset_id: asset.id,
    meter: 'browser_run',
    quantity: rows.reduce((n, r) => n + r.count, 0),
  });

  return json({ ok: true, stored: rows.length, max: MAX_EVENTS });
});
