#!/usr/bin/env python3
"""Generate the Merik blog: article pages, the blog index, and sitemap.xml.

Forty posts share one template, so schema, nav, footer, related links and the
sitemap can never drift apart. Article bodies for the posts this script owns
live in blog_posts.py; the older hand-written posts are listed in CARDS only,
so the index and sitemap still cover them.

    python3 scripts/gen_blog.py

ponytail: regenerates the whole blog every run — it's 40 files, a diff is the
check. Add incremental output only if that stops being instant.
"""
import html
import pathlib
import re

from blog_posts import POSTS
from site_chrome import CHROME_JS, footer, header

ROOT = pathlib.Path(__file__).resolve().parent.parent
BLOG = ROOT / "blog"
SITE = "https://www.merik.in"

# --- Card metadata for every post, in blog-index display order. ---------------
# (slug, category, image, card title, card blurb). Posts generated by this
# script also appear in POSTS; the rest are the earlier hand-written articles.
CARDS = [
    # Attendance
    ("employee-attendance-tracking-small-business", "Attendance", "attendance",
     "How to track employee attendance in a small business (without spreadsheets)",
     "A step-by-step approach to recording attendance accurately every day."),
    ("biometric-vs-gps-vs-manual-attendance", "Attendance", "attendance",
     "Biometric vs GPS vs manual attendance: which should you use?",
     "A practical comparison of the three ways to capture attendance."),
    ("calculating-late-marks-half-days-fairly", "Attendance", "attendance",
     "How to calculate late marks and half-days fairly",
     "A clear, consistent rule set removes disputes and keeps payroll accurate."),
    ("geolocation-attendance-field-teams", "Attendance", "attendance",
     "Geolocation attendance for field and multi-site teams",
     'How to make "present" verifiable without a biometric device per site.'),
    ("attendance-policy-template-small-business", "Attendance", "attendance",
     "Attendance policy template for a small business (copy and adapt)",
     "Every clause a working attendance policy needs, in plain language."),
    ("attendance-regularisation-corrections", "Attendance", "attendance",
     "Attendance regularisation: fixing a wrong day without breaking trust",
     "How to handle missed punches and corrections with an audit trail."),
    # Payroll
    ("attendance-to-payroll-automation", "Payroll", "payroll",
     "From attendance to payroll: how to stop re-keying numbers every month",
     "How connecting attendance and leave directly to payroll removes errors."),
    ("ctc-vs-in-hand-salary-payslip", "Payroll", "payroll",
     "CTC vs in-hand salary: how to read a payslip (India guide)",
     "What CTC really means and how monthly net pay is calculated."),
    ("payroll-compliance-checklist-india-small-business", "Payroll", "payroll",
     "Payroll compliance checklist for Indian small businesses",
     "PF, ESI, professional tax and TDS — what to get right each month."),
    ("how-to-run-payroll-without-an-accountant", "Payroll", "payroll",
     "How to run payroll for a small team without an accountant",
     "A practical monthly process for founders and office managers."),
    ("common-payroll-mistakes-small-businesses", "Payroll", "payroll",
     "Common payroll mistakes small businesses make",
     "The recurring errors that cost time, money and employee trust."),
    ("payslip-format-what-to-include", "Payroll", "payroll",
     "Payslip format: what every payslip must show (and why)",
     "The line items a payslip needs so an employee can check their own pay."),
    ("loss-of-pay-calculation-explained", "Payroll", "payroll",
     "Loss of pay (LOP): how it's calculated, with worked examples",
     "The per-day divisor argument, settled with actual arithmetic."),
    ("salary-hike-revision-cycle", "Payroll", "payroll",
     "Running a salary hike cycle without guesswork",
     "How to structure revisions, effective dates and arrears cleanly."),
    # Leave
    ("leave-management-small-business", "Leave", "leave",
     "Paid vs unpaid leave: how to manage employee leave in a small business",
     "Track balances, approve requests, and keep monthly payroll accurate."),
    ("how-many-leaves-small-business-india", "Leave", "leave",
     "How many leaves should a small business offer in India?",
     "A practical benchmark for annual, sick and casual leave policies."),
    ("work-from-home-policy-template", "Leave", "leave",
     "Work from home policy: what to include and how to track it",
     "A simple WFH policy template that's easy to enforce."),
    ("sick-leave-vs-casual-leave", "Leave", "leave",
     "Sick leave vs casual leave: what's the difference?",
     "Clearing up the confusion so your leave policy stays consistent."),
    ("leave-encashment-carry-forward", "Leave", "leave",
     "Leave carry-forward and encashment, explained simply",
     "How to stop unused leave turning into an unbudgeted year-end bill."),
    ("company-holiday-calendar-india", "Leave", "leave",
     "How to build a company holiday calendar (India)",
     "Fixed days, restricted holidays, and why payroll needs the calendar."),
    # Tasks
    ("daily-task-tracking-small-teams", "Tasks", "tasks",
     "Daily task tracking for small teams: proof, blockers &amp; accountability",
     "Assign work, capture proof and blockers, and build accountability."),
    ("daily-standups-without-meetings", "Tasks", "tasks",
     "How to run daily standups without a meeting",
     "Get the same visibility as a standup without the calendar invite."),
    ("measuring-productivity-without-micromanaging", "Tasks", "tasks",
     "Measuring productivity without micromanaging",
     "Track outcomes, not screen time, and keep your team's trust."),
    ("timesheets-vs-daily-task-logs", "Tasks", "tasks",
     "Timesheets vs daily task logs: which one does your team need?",
     "Same raw material, very different compliance and usefulness."),
    ("time-estimates-vs-actuals", "Tasks", "tasks",
     "Why your time estimates are always wrong (and how to fix them)",
     "Close the gap between estimated and actual using your own history."),
    # Clients
    ("structuring-clients-and-projects", "Clients", "clients",
     "How to structure clients and projects so reporting actually works",
     "Get the hierarchy right once and every report downstream is free."),
    ("quote-to-invoice-workflow", "Clients", "clients",
     "The quote-to-invoice workflow for a small services business",
     "From line-item quote to sent invoice without retyping anything."),
    ("project-profitability-from-task-hours", "Clients", "clients",
     "Working out project profitability from your task hours",
     "Turn the hours your team already logs into a per-project margin."),
    ("pricing-retainers-from-time-data", "Clients", "clients",
     "How to price a retainer using your own time data",
     "Stop guessing the monthly number — derive it from logged hours."),
    # Assets
    ("it-asset-management-small-business", "Assets", "assets",
     "IT asset management for small businesses: the register you actually need",
     "Who has which laptop, since when, and what comes back at exit."),
    ("software-subscription-spend-management", "Assets", "assets",
     "Software subscription spend: finding the seats nobody uses",
     "A monthly routine that quietly removes 20–30% of SaaS waste."),
    # HR
    ("employee-onboarding-checklist-small-business", "HR", "hr",
     "Employee onboarding checklist for small businesses",
     "What to set up before day one, in week one, and the first month."),
    ("structuring-departments-designations-as-you-scale", "HR", "hr",
     "Structuring departments and designations as you scale",
     "How to organize your team before it gets messy."),
    ("employee-self-service-what-it-means", "HR", "hr",
     "Employee self-service: what it means and why it matters",
     "How self-service removes HR as a bottleneck across the business."),
    ("employee-exit-full-and-final-settlement", "HR", "hr",
     "Employee exit and full &amp; final settlement",
     "What to check, calculate, and how to close out cleanly."),
    ("choosing-hr-software-small-business-checklist", "HR", "hr",
     "Choosing HR software for a small business: a buyer's checklist",
     "What to look for before picking a workforce platform."),
    ("monthly-performance-review-process", "HR", "performance",
     "A monthly performance review process that takes 20 minutes",
     "Reviews grounded in the work already logged, not in memory."),
    ("workforce-data-security-checklist", "HR", "security",
     "Workforce data security: what to check before you upload your team",
     "The questions to ask any HR tool holding your salaries and IDs."),
    # AI & migration
    ("ai-in-hr-software-what-actually-helps", "AI", "ai",
     "AI in HR software: what actually helps, and what's theatre",
     "Where a language model earns its place — and where it must not go."),
    ("spreadsheet-to-workforce-software-migration", "AI", "ai",
     "Migrating from spreadsheets to workforce software: a 30-day plan",
     "A week-by-week migration that doesn't blow up your next payroll."),
]

CARD_BY_SLUG = {c[0]: c for c in CARDS}
CATEGORIES = ["Attendance", "Payroll", "Leave", "Tasks", "Clients", "Assets", "HR", "AI"]

HEAD_COMMON = """<script async src="https://www.googletagmanager.com/gtag/js?id=G-5L9G7GMZWD"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag("js", new Date());
  gtag("config", "G-5L9G7GMZWD");
</script>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script>document.documentElement.className+=' js';</script>"""





def j(s):
    """Escape a string for embedding in JSON-LD."""
    return (s.replace("\\", "\\\\").replace('"', '\\"')
             .replace("\n", " ").replace("&amp;", "&").replace("&#8377;", "₹"))


def strip_tags(s):
    return re.sub(r"<[^>]+>", " ", s)


def read_time(post):
    words = len(strip_tags(
        post["lede"] + " ".join(b for _, _, b in post["sections"])
        + " ".join(a for _, a in post["faqs"]) + post["merik"]
    ).split())
    return max(3, round(words / 220))


def card_html(slug, prefix="/"):
    slug_, cat, img, title, blurb = CARD_BY_SLUG[slug]
    return f"""      <a class="blog-card" data-cat="{cat}" href="/blog/{slug}">
        <img class="thumb" src="{prefix}assets/images/blog/{img}.svg" alt="{html.escape(strip_tags(title).strip())}" width="400" height="240" loading="lazy">
        <div class="bc-body"><span class="tag2">{cat}</span>
        <h3>{title}</h3>
        <p>{blurb}</p></div>
      </a>"""


def build_post(p):
    slug = p["slug"]
    url = f"{SITE}/blog/{slug}"
    _, cat, img, card_title, _ = CARD_BY_SLUG[slug]
    mins = read_time(p)

    faq_ld = ",\n      ".join(
        '{"@type":"Question","name":"%s","acceptedAnswer":{"@type":"Answer","text":"%s"}}'
        % (j(q), j(strip_tags(a).strip()))
        for q, a in p["faqs"]
    )

    graph = [
        '{"@type":"BlogPosting","@id":"%s#post","headline":"%s","description":"%s","datePublished":"%s","dateModified":"%s","author":{"@type":"Organization","name":"Merik","@id":"%s/#org"},"publisher":{"@id":"%s/#org"},"mainEntityOfPage":"%s","image":"%s/assets/images/blog/%s.svg","articleSection":"%s","keywords":"%s","wordCount":%d,"timeRequired":"PT%dM","isPartOf":{"@id":"%s/blog/#blog"},"inLanguage":"en"}'
        % (url, j(p["title"]), j(p["desc"]), p["published"], p["modified"], SITE, SITE,
           url, SITE, img, cat, j(p["keywords"]),
           len(strip_tags(" ".join(b for _, _, b in p["sections"])).split()), mins, SITE),
        '{"@type":"BreadcrumbList","itemListElement":[\n      {"@type":"ListItem","position":1,"name":"Home","item":"%s/"},\n      {"@type":"ListItem","position":2,"name":"Blog","item":"%s/blog/"},\n      {"@type":"ListItem","position":3,"name":"%s","item":"%s"}]}'
        % (SITE, SITE, j(p["crumb"]), url),
        '{"@type":"FAQPage","mainEntity":[\n      %s]}' % faq_ld,
    ]
    if p.get("howto"):
        steps = ",\n      ".join(
            '{"@type":"HowToStep","position":%d,"name":"%s","text":"%s"}' % (i + 1, j(n), j(t))
            for i, (n, t) in enumerate(p["howto"]["steps"])
        )
        graph.append(
            '{"@type":"HowTo","name":"%s","description":"%s","step":[\n      %s]}'
            % (j(p["howto"]["name"]), j(p["howto"].get("desc", p["desc"])), steps)
        )

    toc = "\n".join(
        f'      <li><a href="#{sid}">{stitle}</a></li>' for sid, stitle, _ in p["sections"]
    )
    body = "\n\n".join(
        f'    <h2 id="{sid}">{stitle}</h2>\n{sbody}' for sid, stitle, sbody in p["sections"]
    )
    takeaways = "\n".join(f"      <li>{t}</li>" for t in p["takeaways"])
    facts = "\n".join(
        f"      <tr><th>{k}</th><td>{v}</td></tr>" for k, v in p["facts"]
    )
    faqs = "\n".join(
        f"      <details{' open' if i == 0 else ''}><summary>{q}</summary><p>{a}</p></details>"
        for i, (q, a) in enumerate(p["faqs"])
    )
    related = "\n".join(card_html(s) for s in p["related"])

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
{HEAD_COMMON}
<title>{p["title"]}</title>
<meta name="description" content="{p["desc"]}">
<meta name="keywords" content="{p["keywords"]}">
<meta name="author" content="Merik">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
<meta name="theme-color" content="#D93A31">
<link rel="canonical" href="{url}">
<link rel="icon" type="image/png" href="/assets/images/logo.png">
<meta property="og:type" content="article">
<meta property="og:site_name" content="Merik">
<meta property="og:title" content="{p["og_title"]}">
<meta property="og:description" content="{p["og_desc"]}">
<meta property="og:url" content="{url}">
<meta property="og:image" content="{SITE}/assets/images/blog/{img}.svg">
<meta property="og:locale" content="en_IN">
<meta property="article:published_time" content="{p["published"]}">
<meta property="article:modified_time" content="{p["modified"]}">
<meta property="article:section" content="{cat}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{p["og_title"]}">
<meta name="twitter:description" content="{p["og_desc"]}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/css/site.css?v=5">
<script type="application/ld+json">
{{
  "@context":"https://schema.org",
  "@graph":[
    {",\n    ".join(graph)}
  ]
}}
</script>
</head>
<body>

<div class="progress" id="progress" aria-hidden="true"></div>

{header("blog")}

<div class="page-hero">
  <div class="wrap">
    <nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span> <a href="/blog/">Blog</a><span>›</span> {p["crumb"]}</nav>
    <div class="eyebrow">{cat}</div>
    <h1>{p["h1"]}</h1>
    <p class="lead">{p["lead"]}</p>
  </div>
</div>

<section>
  <div class="wrap prose">
    <img class="article-hero-img" src="/assets/images/blog/{img}.svg" alt="{html.escape(p["img_alt"])}" width="640" height="384">
    <p class="post-meta">Published {p["published_h"]} · Updated {p["modified_h"]} · Merik team · {mins} min read</p>
    <p class="lede">{p["lede"]}</p>

    <div class="keytakeaways">
      <b>Key takeaways</b>
      <ul>
{takeaways}
      </ul>
    </div>

    <nav class="toc" aria-label="On this page">
      <b>On this page</b>
      <ol>
{toc}
      </ol>
    </nav>

{body}

    <h2 id="facts">Quick reference</h2>
    <table class="facts">
{facts}
    </table>

    <h2 id="faq">Frequently asked questions</h2>
    <div class="faq" style="margin:0 0 24px">
{faqs}
    </div>

    <h2 id="merik">How Merik handles it</h2>
{p["merik"]}

    <p><a class="btn btn-primary" href="/app/">Create your workspace →</a></p>
    <p style="margin-top:10px"><a href="/#talk-to-us" style="color:var(--brand);font-weight:600">Or talk to us about your team →</a></p>
  </div>
</section>

<section class="related soft">
  <div class="wrap">
    <h2>Related articles</h2>
    <div class="grid">
{related}
    </div>
  </div>
</section>

{footer()}

{CHROME_JS}
</body>
</html>
"""


def build_index():
    cards = "\n".join(card_html(c[0]) for c in CARDS)
    filters = "\n".join(
        f'      <button data-cat="{c}">{c}</button>' for c in CATEGORIES
    )
    items = ",\n      ".join(
        '{"@type":"ListItem","position":%d,"url":"%s/blog/%s","name":"%s"}'
        % (i + 1, SITE, c[0], j(strip_tags(c[3]).strip()))
        for i, c in enumerate(CARDS)
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
{HEAD_COMMON}
<title>Merik Blog | {len(CARDS)} Guides on Workforce, Attendance, Payroll &amp; HR</title>
<meta name="description" content="{len(CARDS)} practical guides on workforce management, attendance, leave, payroll, daily tasks, clients, assets and HR for small and growing businesses — from the Merik team.">
<meta name="keywords" content="workforce management blog, attendance tracking guide, payroll automation, HR software for small business, leave management tips, task tracking guide, Merik blog">
<meta name="author" content="Merik">
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
<meta name="theme-color" content="#D93A31">
<link rel="canonical" href="{SITE}/blog/">
<link rel="icon" type="image/png" href="/assets/images/logo.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Merik">
<meta property="og:title" content="Merik Blog — Workforce, Attendance, Payroll &amp; HR Guides">
<meta property="og:description" content="Practical guides on workforce management, attendance, leave, payroll and HR for small and growing businesses.">
<meta property="og:url" content="{SITE}/blog/">
<meta property="og:image" content="{SITE}/assets/images/logo.png">
<meta property="og:locale" content="en_IN">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Merik Blog">
<meta name="twitter:description" content="Guides on workforce management, attendance, leave, payroll and HR for small business.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/assets/css/site.css?v=5">
<script type="application/ld+json">
{{
  "@context":"https://schema.org",
  "@graph":[
    {{"@type":"Blog","@id":"{SITE}/blog/#blog","url":"{SITE}/blog/","name":"Merik Blog","description":"Guides on workforce management, attendance, leave, payroll, tasks, clients, assets and HR for small and growing businesses.","publisher":{{"@id":"{SITE}/#org"}},"isPartOf":{{"@id":"{SITE}/#website"}},"inLanguage":"en"}},
    {{"@type":"BreadcrumbList","itemListElement":[
      {{"@type":"ListItem","position":1,"name":"Home","item":"{SITE}/"}},
      {{"@type":"ListItem","position":2,"name":"Blog","item":"{SITE}/blog/"}}]}},
    {{"@type":"ItemList","name":"Merik workforce guides","numberOfItems":{len(CARDS)},"itemListElement":[
      {items}]}}
  ]
}}
</script>
</head>
<body>

<div class="progress" id="progress" aria-hidden="true"></div>

{header("blog")}

<div class="page-hero">
  <div class="wrap">
    <nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>›</span> Blog</nav>
    <div class="eyebrow">Merik Blog</div>
    <h1>Guides for running your <span class="accent">workforce</span></h1>
    <p class="lead">{len(CARDS)} practical, no-fluff guides on attendance, leave, payroll, daily tasks, clients, assets and HR — for small and growing businesses replacing spreadsheets with one workspace.</p>
  </div>
</div>

<section class="features">
  <div class="wrap">
    <div class="blog-search">
      <input id="blogSearch" type="search" placeholder="Search {len(CARDS)} guides — payroll, leave, attendance…" aria-label="Search the blog">
    </div>
    <div class="blog-filters" id="blogFilters">
      <button class="on" data-cat="all">All ({len(CARDS)})</button>
{filters}
    </div>
    <div class="grid" id="blogGrid">

{cards}

    </div>
    <p class="blog-empty" id="blogEmpty">No guides match that search. Try “payroll”, “leave” or “attendance”.</p>
  </div>
</section>

<section class="features" style="padding-top:0">
  <div class="wrap">
    <div class="cta-wrap">
      <h2>Run your workforce the simple way</h2>
      <p>Create your company workspace and bring employees, attendance, leave, payroll and tasks together.</p>
      <div class="hero-cta">
        <a class="btn btn-primary" href="/app/">Create your workspace →</a>
        <a class="btn btn-ghost" href="/features">Explore features</a>
      </div>
    </div>
  </div>
</section>

{footer()}

{CHROME_JS}
<script>
  /* Category filter + free-text search, applied together. */
  var filterBtns=document.querySelectorAll('#blogFilters button');
  var cards=Array.prototype.slice.call(document.querySelectorAll('#blogGrid .blog-card'));
  var search=document.getElementById('blogSearch');
  var empty=document.getElementById('blogEmpty');
  var cat='all';
  cards.forEach(function(c){{c.dataset.text=c.textContent.toLowerCase();}});
  function apply(){{
    var q=(search.value||'').trim().toLowerCase();
    var shown=0;
    cards.forEach(function(c){{
      var ok=(cat==='all'||c.getAttribute('data-cat')===cat)&&(!q||c.dataset.text.indexOf(q)>-1);
      c.style.display=ok?'':'none';
      if(ok)shown++;
    }});
    empty.style.display=shown?'none':'block';
  }}
  filterBtns.forEach(function(btn){{
    btn.addEventListener('click',function(){{
      filterBtns.forEach(function(b){{b.classList.remove('on');}});
      btn.classList.add('on');
      cat=btn.getAttribute('data-cat');
      apply();
      if(typeof gtag==='function')gtag('event','blog_filter',{{category:cat}});
    }});
  }});
  search.addEventListener('input',apply);
</script>
</body>
</html>
"""


def build_sitemap(posts_by_slug):
    def url(loc, lastmod, freq, prio):
        return (f"  <url>\n    <loc>{loc}</loc>\n    <lastmod>{lastmod}</lastmod>\n"
                f"    <changefreq>{freq}</changefreq>\n    <priority>{prio}</priority>\n  </url>")

    newest = max(p["modified"] for p in posts_by_slug.values())
    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
        url(f"{SITE}/", newest, "weekly", "1.0"),
        url(f"{SITE}/features", "2026-07-11", "monthly", "0.9"),
        url(f"{SITE}/how-it-works", "2026-07-11", "monthly", "0.8"),
        url(f"{SITE}/modules", "2026-07-11", "monthly", "0.8"),
        url(f"{SITE}/pricing", newest, "monthly", "0.9"),
        url(f"{SITE}/roi", newest, "monthly", "0.8"),
        url(f"{SITE}/blog/", newest, "weekly", "0.7"),
    ]
    for slug, _, _, _, _ in CARDS:
        p = posts_by_slug.get(slug)
        out.append(url(f"{SITE}/blog/{slug}", p["modified"] if p else "2026-07-16",
                       "monthly", "0.6"))
    out.append("</urlset>")
    return "\n".join(out) + "\n"


def main():
    by_slug = {p["slug"]: p for p in POSTS}
    missing = [s for s in by_slug if s not in CARD_BY_SLUG]
    assert not missing, f"post without a CARDS entry: {missing}"
    for p in POSTS:
        for r in p["related"]:
            assert r in CARD_BY_SLUG, f"{p['slug']} links to unknown post {r}"
        (BLOG / f"{p['slug']}.html").write_text(build_post(p), encoding="utf-8")
    (BLOG / "index.html").write_text(build_index(), encoding="utf-8")
    (ROOT / "sitemap.xml").write_text(build_sitemap(by_slug), encoding="utf-8")
    print(f"wrote {len(POSTS)} posts, blog/index.html ({len(CARDS)} cards), sitemap.xml")


if __name__ == "__main__":
    main()
